import React, { useState, useRef, useEffect } from 'react';
import type { Candidate } from '../api/client';
import { generateDMStream } from '../api/client';

interface DMComposerProps {
  candidate: Candidate;
  onClose: () => void;
}

export function DMComposer({ candidate, onClose }: DMComposerProps) {
  const [customContext, setCustomContext] = useState('');
  const [tone, setTone] = useState<'professional' | 'casual' | 'enthusiastic'>('professional');
  const [generatedMessage, setGeneratedMessage] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [charCount, setCharCount] = useState(0);
  const [showConfirmation, setShowConfirmation] = useState(false);
  const messageRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef(false);

  // Auto-generate on mount
  useEffect(() => {
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, []);

  // Auto-scroll as message generates
  useEffect(() => {
    if (messageRef.current) {
      messageRef.current.scrollTop = messageRef.current.scrollHeight;
    }
  }, [generatedMessage]);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setGeneratedMessage('');
    setCharCount(0);

    try {
      await generateDMStream(candidate.handle, customContext || '', tone, {
        onContent: (content) => {
          setGeneratedMessage(prev => prev + content);
        },
        onDone: (message, _url, count) => {
          setGeneratedMessage(message);
          setCharCount(count);
          setIsGenerating(false);
        },
        onError: (error) => {
          setGeneratedMessage(`Error: ${error}`);
          setIsGenerating(false);
        },
      });
    } catch {
      setGeneratedMessage('Failed to generate message. Please try again.');
      setIsGenerating(false);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedMessage);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for HTTP
      const textarea = document.createElement('textarea');
      textarea.value = generatedMessage;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleSendDM = () => {
    // Show confirmation before opening X
    setShowConfirmation(true);
  };

  const handleConfirmSend = () => {
    // Open X DM compose with pre-filled message
    const dmUrl = `https://x.com/messages/compose?recipient_id=&text=${encodeURIComponent(generatedMessage)}`;
    window.open(dmUrl, '_blank');
    setShowConfirmation(false);
  };

  return (
    <div style={styles.overlay} onClick={onClose}>
      <div style={styles.modal} onClick={e => e.stopPropagation()}>
        <button style={styles.closeButton} onClick={onClose}>
          &times;
        </button>

        <div style={styles.header}>
          <h2 style={styles.title}>Compose DM to @{candidate.handle}</h2>
          <p style={styles.subtitle}>
            {candidate.summary.substring(0, 100)}
            {candidate.summary.length > 100 ? '...' : ''}
          </p>
        </div>

        <div style={styles.content}>
          {/* Generated Message - shown first */}
          <div style={styles.section}>
            <div style={styles.labelRow}>
              <label style={styles.label}>Generated Message</label>
              {charCount > 0 && (
                <span
                  style={{
                    ...styles.charCount,
                    color: charCount > 280 ? 'var(--accent-orange)' : 'var(--text-muted)',
                  }}
                >
                  {charCount} characters
                </span>
              )}
            </div>
            <div style={styles.messageBox} ref={messageRef}>
              {isGenerating && !generatedMessage ? (
                <div style={styles.loadingContainer}>
                  <div style={styles.spinner} />
                  <span style={styles.loadingText}>Generating personalized message...</span>
                </div>
              ) : (
                <pre style={styles.messageText}>
                  {generatedMessage}
                  {isGenerating && <span style={styles.cursor}>|</span>}
                </pre>
              )}
            </div>

            {!isGenerating && generatedMessage && !generatedMessage.startsWith('Error') && (
              <div style={styles.actionButtons}>
                <button style={styles.copyButton} onClick={handleCopy}>
                  {copied ? 'Copied!' : 'Copy Message'}
                </button>
                <button style={styles.xButton} onClick={handleSendDM}>
                  Send DM to @{candidate.handle}
                </button>
              </div>
            )}

            {/* Confirmation Dialog */}
            {showConfirmation && (
              <div style={styles.confirmationOverlay}>
                <div style={styles.confirmationBox}>
                  <h3 style={styles.confirmTitle}>Ready to send?</h3>
                  <p style={styles.confirmText}>
                    This will open X with your message ready to send to @{candidate.handle}
                  </p>
                  <div style={styles.confirmPreview}>
                    <pre style={styles.previewText}>{generatedMessage}</pre>
                  </div>
                  <div style={styles.confirmButtons}>
                    <button
                      style={styles.cancelButton}
                      onClick={() => setShowConfirmation(false)}
                    >
                      Cancel
                    </button>
                    <button style={styles.confirmSendButton} onClick={handleConfirmSend}>
                      Open X & Send
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Customization Section - collapsible refinements */}
          <details style={styles.details}>
            <summary style={styles.summary}>Customize & Regenerate</summary>

            {/* Tone Selector */}
            <div style={styles.section}>
              <label style={styles.label}>Tone</label>
              <div style={styles.toneButtons}>
                {(['professional', 'casual', 'enthusiastic'] as const).map(t => (
                  <button
                    key={t}
                    style={{
                      ...styles.toneButton,
                      ...(tone === t ? styles.toneButtonActive : {}),
                    }}
                    onClick={() => setTone(t)}
                  >
                    {t.charAt(0).toUpperCase() + t.slice(1)}
                  </button>
                ))}
              </div>
            </div>

            {/* Optional Context */}
            <div style={styles.section}>
              <label style={styles.label}>Additional Context (optional)</label>
              <textarea
                style={styles.textarea}
                value={customContext}
                onChange={e => setCustomContext(e.target.value)}
                placeholder="Add specific job details, team info, or personalization..."
                rows={3}
              />
            </div>

            {/* Regenerate Button */}
            <button
              style={{
                ...styles.regenerateButton,
                opacity: isGenerating ? 0.6 : 1,
              }}
              onClick={handleGenerate}
              disabled={isGenerating}
            >
              {isGenerating ? 'Generating...' : 'Regenerate Message'}
            </button>
          </details>
        </div>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: '40px 20px',
    overflowY: 'auto',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: 'var(--bg-primary)',
    borderRadius: '16px',
    maxWidth: '600px',
    width: '100%',
    position: 'relative',
    border: '1px solid var(--border-color)',
  },
  closeButton: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    background: 'none',
    border: 'none',
    fontSize: '28px',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '4px 12px',
    borderRadius: '8px',
  },
  header: {
    padding: '32px 32px 20px',
    borderBottom: '1px solid var(--border-color)',
  },
  title: {
    fontSize: '20px',
    fontWeight: 600,
    margin: 0,
    color: 'var(--text-primary)',
  },
  subtitle: {
    fontSize: '14px',
    color: 'var(--text-secondary)',
    marginTop: '8px',
    lineHeight: 1.5,
  },
  content: {
    padding: '24px 32px 32px',
  },
  section: {
    marginBottom: '24px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: '8px',
  },
  labelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  hint: {
    fontSize: '13px',
    color: 'var(--text-muted)',
    marginBottom: '12px',
    marginTop: 0,
  },
  charCount: {
    fontSize: '12px',
    fontWeight: 400,
  },
  textarea: {
    width: '100%',
    padding: '14px',
    fontSize: '14px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    color: 'var(--text-primary)',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  toneButtons: {
    display: 'flex',
    gap: '8px',
  },
  toneButton: {
    padding: '8px 16px',
    fontSize: '13px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  toneButtonActive: {
    backgroundColor: 'var(--accent-primary)',
    color: '#000',
    borderColor: 'var(--accent-primary)',
  },
  details: {
    marginTop: '8px',
    borderTop: '1px solid var(--border-color)',
    paddingTop: '16px',
  },
  summary: {
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    padding: '8px 0',
    userSelect: 'none',
  },
  regenerateButton: {
    width: '100%',
    padding: '12px',
    fontSize: '14px',
    fontWeight: 500,
    backgroundColor: 'var(--bg-tertiary)',
    color: 'var(--text-primary)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  messageBox: {
    padding: '16px',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    maxHeight: '200px',
    overflowY: 'auto',
  },
  messageText: {
    margin: 0,
    fontSize: '14px',
    lineHeight: 1.6,
    color: 'var(--text-primary)',
    whiteSpace: 'pre-wrap',
    fontFamily: 'inherit',
  },
  cursor: {
    color: 'var(--accent-primary)',
    animation: 'blink 1s infinite',
  },
  actionButtons: {
    display: 'flex',
    gap: '12px',
    marginTop: '16px',
  },
  copyButton: {
    flex: 1,
    padding: '12px',
    fontSize: '14px',
    fontWeight: 500,
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-primary)',
    cursor: 'pointer',
  },
  xButton: {
    flex: 1,
    padding: '12px',
    fontSize: '14px',
    fontWeight: 500,
    backgroundColor: '#000',
    border: '1px solid #333',
    borderRadius: '8px',
    color: 'white',
    cursor: 'pointer',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 16px',
    gap: '16px',
  },
  spinner: {
    width: '32px',
    height: '32px',
    border: '3px solid var(--border-color)',
    borderTopColor: 'var(--accent-primary)',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  loadingText: {
    fontSize: '14px',
    color: 'var(--text-muted)',
  },
  confirmationOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1100,
  },
  confirmationBox: {
    backgroundColor: 'var(--bg-primary)',
    borderRadius: '16px',
    padding: '24px',
    maxWidth: '500px',
    width: '90%',
    border: '1px solid var(--border-color)',
  },
  confirmTitle: {
    fontSize: '18px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: '0 0 8px 0',
  },
  confirmText: {
    fontSize: '14px',
    color: 'var(--text-secondary)',
    margin: '0 0 16px 0',
  },
  confirmPreview: {
    padding: '12px',
    backgroundColor: 'var(--bg-secondary)',
    borderRadius: '8px',
    border: '1px solid var(--border-color)',
    maxHeight: '150px',
    overflowY: 'auto',
    marginBottom: '20px',
  },
  previewText: {
    margin: 0,
    fontSize: '13px',
    lineHeight: 1.5,
    color: 'var(--text-primary)',
    whiteSpace: 'pre-wrap',
    fontFamily: 'inherit',
  },
  confirmButtons: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: 500,
    backgroundColor: 'transparent',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  confirmSendButton: {
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: 500,
    backgroundColor: 'var(--accent-primary)',
    border: 'none',
    borderRadius: '8px',
    color: '#000',
    cursor: 'pointer',
  },
};
